# Generated by Django 3.0.2 on 2020-01-22 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instagram', '0002_loggedinuser_dbuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='loggedin_user_comment',
        ),
        migrations.RemoveField(
            model_name='loggedinuser',
            name='name',
        ),
        migrations.AddField(
            model_name='comments',
            name='db_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instagram.DBUSER'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loggedinuser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loggedinuser',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
