# Generated by Django 3.0.2 on 2020-01-31 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_auto_20200131_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment_section',
        ),
        migrations.AddField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instagram.Post'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.CharField(max_length=200),
        ),
    ]
