# Generated by Django 3.0.2 on 2020-01-22 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instagram', '0003_auto_20200122_0747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loggedinuser',
            name='dbuser',
        ),
        migrations.AddField(
            model_name='dbuser',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dbuser',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instagram.loggedinUser'),
        ),
        migrations.AddField(
            model_name='loggedinuser',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
