# Generated by Django 3.0.2 on 2020-02-03 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0004_auto_20200131_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='picture',
        ),
    ]
