# Generated by Django 3.0.2 on 2020-01-22 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0004_auto_20200122_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loggedinuser',
            old_name='Bio',
            new_name='bio',
        ),
    ]
