# Generated by Django 3.0.2 on 2020-01-25 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0006_auto_20200125_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loggedinuser',
            name='name',
        ),
    ]
