# Generated by Django 3.0.2 on 2020-01-25 10:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    
    
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instagram', '0007_remove_loggedinuser_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='loggedinUser',
            new_name='Profile',
        ),
    ]
