# Generated by Django 3.0.2 on 2020-01-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0009_auto_20200125_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='uploaded_photos')),
                ('caption', models.TextField(max_length=500)),
            ],
        ),
    ]
