# Generated by Django 3.0.2 on 2020-01-28 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0014_delete_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dbuser',
            name='user_profile',
        ),
    ]
