# Generated by Django 3.0.2 on 2020-01-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0015_remove_dbuser_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbuser',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
