# Generated by Django 3.0.2 on 2020-01-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0017_pictures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictures',
            name='image',
        ),
        migrations.AddField(
            model_name='pictures',
            name='image_url',
            field=models.URLField(max_length=250, null=True),
        ),
    ]
