# Generated by Django 3.0.2 on 2020-01-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0018_auto_20200128_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='caption',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
