# Generated by Django 3.0.2 on 2020-01-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0019_pictures_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
